wpReplacements = ->
  # Replace certain WP elements that are autogenerated with proper
  # ones here
  menuClass
  paperHTML = "<paper-tabs id='menu-main'>"
  i = 0
  $("#menu-main li a").each ->
    href = $(this).attr("href")
    name = $(this).text()
    className = $(this).parent().attr("class")
    id = $(this).parent().attr('id')
    paperHTML += "<paper-tab class='#{className}' id='#{id}' onclick=\"openLink('#{href}')\">#{name}</paper-tab>"
    i++
    if i is $("#menu-main li").length()
      paperHTML += "</paper-tabs>"
      $("#primary-navigation").html(paperHTML)

$ ->
  wpReplacements()
