wpReplacements = ->
  # Replace certain WP elements that are autogenerated with proper
  # ones here
  i = 0
  $("paper-tab").each ->
    href = $(this).attr("data-url")
    if href is window.location.href
      document.querySelector("#menu-main").setAttribute("selected",i)
      console.log("Selected element #{i}")


$ ->
  wpReplacements()
  $("#searchsubmit").click ->
    $("#sidebar-search-form").submit()
  $("#s").keyup (e) ->
    code = e.keyCode || e.which
    if code is 13 then $("#sidebar-search-form").submit()
